name: Releaser

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets-linux
          path: |
            target/release/nat2
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets-windows
          path: |
            target/release/*.exe
  release:
    name: Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Collect files
        uses: actions/download-artifact@v4

      - id: get_version
        name: Get version
        uses: jannemattila/get-version-from-tag@v4

      - name: Compress files
        run: |
          tar -czvf nat2-${{ steps.get_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz -C ./assets-linux ./nat2
          zip -j nat2-${{ steps.get_version.outputs.version }}-x86_64-pc-windows-msvc.zip ./assets-windows/nat2.exe

      - name: Upload release assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            ./*.tar.gz
            ./*.zip
